name: buildzip

# 触发条件
on:
  workflow_dispatch:

  schedule:
    - cron: '* * */2 * *'
    # 表达式生成  https://crontab.guru/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 执行任务
      run: |
        mkdir Kotlin-Files && cd Kotlin-Files
        rm Release.zip
        wget -O Release.zip https://github.com/OTRSU/Software/archive/refs/heads/main.zip
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add .
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')拉取更新"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
